= Aron Wall's God and Time Series

.Source
http://www.wall.org/~aron/blog/god-and-time-i-metaphysics/

== God and Time I: Metaphysics

* God is not a part of time, but is eternal and unchanging. However, he united himself to a human being, Christ, who suffered and died for us.
* There are two prevailing views on time: A-theory and B-theory:
. *A-theory*: Also known as _presentism_, A-theory claims that time flows from the past to the future in such a way that only the present time is real. The past _was_ real and the future _will_ be real due to the flowing of time from past to future. This can be called "tensed" time.
. *B-theory*: Also known as _eternalism_ or Minkowskian spacetime, B-theory claims that all times exist equally, and that the present time is equivalent to a location in the timestream. This can be called "untensed" time.
* An A-theorist essentially claims that since the past and future do not exist, the present moment is the only thing that ever exists. The past and future are not real.
* Wall believes B-theory is the only option that makes logical sense because it asserts that all of time is real, regardless of how we feel that time is ever flowing and changing through our subjective experience.
* B-theory of time fits well if God is the eternal and fundamental reality, because he himself is eternal.
* Time exists contingently as part of the physical world because God created it.

== God and Time II: Special Relativity

* The symmetry of spacetime implies the following proposal:
. If God is omnipresent, and
. If the Lorentz boost is a valid symmetry of reality, then inevitably:
. God is omnitemporal.
* Special relativity seems to suggest that if God has no definite position in space, he must not also be in time.
