= Historicity of Adam

== Aron Wall's Thoughts

"My own pet theory is that maybe the origin of human beings began when God chose to speak verbally to a particular human being (or perhaps even a literal married couple) thus granting them language and (therefore) a greatly advanced ability to think, all wrapped up in the same package with communion with God. One interesting feature this idea is that it allows humanness to be transmitted "horizontally" within a single generation to the others living at the same time." -- http://www.wall.org/~aron/blog/flesh-and-spirit-ii-original-sin/

== De Novo Adam: Imago Dei or Genetic Progenator

Source: John Rood's comments in response to this article: link:https://biologos.org/blogs/deborah-haarsma-the-presidents-notebook/a-flawed-mirror-a-response-to-the-book-theistic-evolution[A Flawed Mirror: A Response to the Book "Theistic Evolution"]

"When I read that sentence, I was surprised, frustrated, and just deeply disappointed, because it seemed initially to me to be saying that the “de novo” view necessarily includes an affirmation that Adam and Eve were the “sole genetic progenitors.” Wouldn’t you agree that it is entirely possible for someone to believe in the “de novo” creation of Adam and Even without believing that they are the “sole genetic progenitors”, that God could have created them specially (just as Jesus’ virgin birth was special) and their children could have intermarried with other hominids who had evolved in accord with evolutionary science? In fact, this is the view I currently find most convincing. In referring to the “traditional de novo view”, were you distinguishing it from other non traditional “de novo” views? I can see now that perhaps that is what was meant, although I didn’t see that at first and I don’t think it is clear.

Ultimately, it’s not the terms here that are important to me, but rather the concepts behind them. Although we are dealing with a subtle distinction, I’ve become convinced that the failure to make this distinction clear over the years may have been the source of a fairly profound amount of unnecessary disagreement. I myself suffered much cognitive dissonance in trying to reconcile population genetics with the claims of Romans 5, and the solution came in realizing that I could affirm that affirm Adam and Eve as the sole Imago Dei progenitors without having to affirm that they were the sole genetic progenitors. Perhaps you have found other ways of reconciling these things, but I haven’t found any others that were satisfying, and I suspect many others are in the same boat as me.

I want to highlight that I am not alone in wishing that Biologos would have more clarity on the “de novo”/”sole genetic progenitor” distinction. I believe it was this issue that Josh Swamidass was addressing in his defense of Tim Keller after Biologos’ interaction with a Gospel Coalition video last fall http://peacefulscience.org/defense-tim-keller/ I was hopeful that the conversation then marked a turning point. I’m still hopeful, that we can eventually find a way to make this distinction more clear."

== Resources to Read:

* link:http://edwardfeser.blogspot.com/2011/09/modern-biology-and-original-sin-part-i.html["Modern Biology and Original Sin, Part 1" -- Ed Feser's Blog]
* link:http://www.copticchurch.net/topics/theology/incarnation_st_athanasius.pdf[St. Athanasius's The Incarnation (PDF)]
* link:http://www.samizdat.qc.ca/cosmos/philo/PDFs/ProblemofPain_CSL.pdf[The Problem of Pain by C.S. Lewis]
* link:http://commonsenseatheism.com/wp-content/uploads/2009/05/inwagen-the-problem-of-evil.pdf[The Problem of Evil by Peter Van Inwagen]
