= Michael Licona vs Luke Muehlhauser Debate

== Licona's Arguments

* There are "4 + 1" arguments for the resurrection, which are so strongly evident that they have persuaded a strong majority of scholars to accept them as fact:
. Nearly 100% recognize that Jesus died by crucifixion
. Nearly 100% recognize that the disciples believe that Jesus rose and appeared to them after death
. Nearly 100% grant that Paul was a skeptic who converted to Christianity because he believed Jesus rose and appeared to him
. Nearly 90% believe that James (Jesus' half brother) was a skeptic prior to the resurrection and that he converted to Christianity following a post-resurrection appearance of Jesus
. Nearly 66% believe that there was an empty tomb
* The disciples didn't come to their belief through testimony or indirect experience, but rather through direct knowledge of the person of Jesus, which provides some uniqueness to the event.
* Many people can claim to have experienced supernatural phenomena, and Licona wouldn't reject all of it.
* Paul received the eyewitness accounts of Jesus' resurrection and his appearances within 3-5 years after Jesus' death, thus limiting the opportunity for legendary elements to appear in the disciple's testimony.

== Muehlhauser's Arguments

* The fact that people convert to different religions can't be used as evidence, neither can people's very strongly held convictions, or believers' willingness to die for their beliefs.
* Many people across history, for example Muhammad, said that they had a vision or experience of supernatural phenomena, so how is the testimony of the disciples any better proof for the resurrection of Jesus?
* While there are differences between the account of the disciples and other religions' or persons' accounts of their religions experience, ultimately these differences do not provide better or worse evidence for the truth of the disciples' account.
* Muehlhauser had his own supernatural experience while he was a Christian, but he attributes the experience to his brain's "software." It could have been a mental simulation, shadows and light coming through the window, a dream, etc. He argues it's just much more likely that it was a brain phenomena or can be attributed to an undiscovered future naturalistic explanation.
* History has taught us that we used to explain natural events with supernatural causes or phenomena. As science has developed clear answers to these phenomena, it's plausible to assume that most of our currently unexplained phenomena will end up being explained naturalistically.
* Temple of Delphi example: if there were several witnesses who wrote down an account instead of one, would a Christian take that as seriously as they take the historical account for the resurrection of Jesus?
* Two modern miraculous examples with substantially more evidence and witnesses include the Miracle of the Sun in Portugal in 1917 and the Hindu Milk Miracle in India in 1995.
* When we have naturalistic explanations of the data, then we should prefer these over the supernatural ones.
* From probability, only 1 in 10 billion people have raised from the dead, so this makes it extremely unlikely to have occurred from the standpoint of mathematical probability.
* Modern examples of cults have demonstrated that people can come together and lie or conspire, in part due to the influence of a charismatic leader.
* When something is claimed to have happened that contradicts with everything we know from experience and is possible from a naturalistic perspective, it requires extraordinary evidence.
* Muehlhauser's preferred explanation is that Jesus was very charismatic, gathered a very committed group of people together who believed in his claims, and when Jesus was killed, they were very distraught and experienced visions or hallucinations after his death. Then they met together and started telling each other about their hallucinations. Everyone's shared experiences corroborated their validity, and these experiences accumulated additional legendary details very quickly after Jesus' death.
* The resurrection story arose very closely after the death of Jesus, as verified by Paul's account in 1 Corinthians 15:3-8.
* Within the few years after Jesus' death, it's plausible that resurrection legends developed.
* There is evidence in the modern era where people in cults have started to believe their own lies, and it's possible that happened with the early Christians, either through intentional or unintentional self-deception.
